#ifndef CAN_HAL_H_
#define CAN_HAL_H_
#include "sdk_project_config.h"
#include "flexcan_driver.h"

typedef enum
{
	CAN_HAL_ULTRASONIC1_CANID = 1,
	CAN_HAL_ULTRASONIC2_CANID,
	CAN_HAL_ULTRASONIC3_CANID,
	CAN_HAL_ULTRASONIC4_CANID,
	CAN_HAL_SPEED_CANID,
	CAN_HAL_RPM_CANID,
	CAN_HAL_DOORSTATES_CANID,
	CAN_HAL_GEAR_SATE_CANID,
	CAN_HAL_REQ_SPEED_CANID,
	CAN_HAL_REQ_RPM_CANID,
	CAN_HAL_REQ_ULTRASONIC1_CANID,
	CAN_HAL_REQ_ULTRASONIC2_CANID,
	CAN_HAL_REQ_ULTRASONIC3_CANID,
	CAN_HAL_REQ_ULTRASONIC4_CANID,
	CAN_HAL_REQ_DOORSTATES_CANID,
	CAN_HAL_REQ_GEARSTATE_CANID
}CAN_HAL_enuCAN_IDS_t;


typedef enum
{
	CAN_HAL_ULTRASONIC1_TX_MB,
	CAN_HAL_ULTRASONIC2_TX_MB,
	CAN_HAL_ULTRASONIC3_TX_MB,
	CAN_HAL_ULTRASONIC4_TX_MB,
	CAN_HAL_SPEED_TX_MB,
	CAN_HAL_RPM_TX_MB,
	CAN_HAL_DOORSTATES_TX_MB,
	CAN_HAL_GEAR_SATE_TX_MB,
	CAN_HAL_REQ_SPEED_TX_MB,
	CAN_HAL_REQ_RPM_TX_MB,
	CAN_HAL_REQ_ULTRASONIC1_TX_MB,
	CAN_HAL_REQ_ULTRASONIC2_TX_MB,
	CAN_HAL_REQ_ULTRASONIC3_TX_MB,
	CAN_HAL_REQ_ULTRASONIC4_TX_MB,
	CAN_HAL_REQ_DOORSTATES_TX_MB,
	CAN_HAL_REQ_GEARSTATE_TX_MB

}CAN_HAL_enuCAN_TX_MB_t;

typedef enum
{
	CAN_HAL_REQ_SPEED_RX_MB = 16,
	CAN_HAL_REQ_RPM_RX_MB,
	CAN_HAL_REQ_ULTRASONIC1_RX_MB,
	CAN_HAL_REQ_ULTRASONIC2_RX_MB,
	CAN_HAL_REQ_ULTRASONIC3_RX_MB,
	CAN_HAL_REQ_ULTRASONIC4_RX_MB,
	CAN_HAL_REQ_DOORSTATES_RX_MB,
	CAN_HAL_REQ_GEARSTATE_RX_MB
}CAN_HAL_enuCAN_RX_MB_t;

typedef void(*CAN_HAL_rxCallBack_t)(CAN_HAL_enuCAN_RX_MB_t);

extern void CAN_HAL_vInit(void);

extern void CAN_HAL_vInstallCallBack(CAN_HAL_rxCallBack_t callBack);


#endif
